/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const OpacifyIndexLazyImport = createFileRoute('/opacify/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OpacifyIndexLazyRoute = OpacifyIndexLazyImport.update({
  path: '/opacify/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/opacify/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/opacify/': {
      id: '/opacify/'
      path: '/opacify'
      fullPath: '/opacify'
      preLoaderRoute: typeof OpacifyIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  OpacifyIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/opacify/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/opacify/": {
      "filePath": "opacify/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
